### ISSUE TITLE
Approve MDAnalysis for fiscal sponsorship

### ISSUE THREAD

**Issue by xorJane** [numfocus/numfocus#33]
# Application to become fiscally sponsored project

Project name: MDAnalysis
[Application](https://drive.google.com/file/d/1YpE0YaMtWSnte_B1QrUIl3E4v_SabaBZ/view)
Project homepage: https://www.mdanalysis.org/

## Criteria

- [x] Be scientifically oriented: The project is an active contributor
  to our mission to scientific research.

MDAnalysis is "written by scientists for scientists". It enables molecular simulations (MD == molecular dynamics) for research in biophysics, biochemistry, and materials science. Currently MDAnalysis has been cited over 800 times.

- [x] Be open: The project must be led openly

The project uses open licensing:

> The MDAnalysis library itself is released under GNU GPL v2 (or a later version at
the user’s choice). We have additional support libraries (see
https://github.com/MDAnalysis/mdanalysis) that are either also GPL (if they
import MDAnalysis) or MIT or BSD-3.

The project has a large contributor and user base:

- 89 people have contributed to MDAnalysis on Github.
- 34 people (per Github states) have added over 1000 lines of code each.
- 115 people subscribe to their developer mailing list.
- 460 people subscribe to their user mailing list.

Project leads come from various institutions. (The 6 signatories for the FSA do not share home institutions.)

Roadmaps and project updates are openly communicated via the project blog:
[https://www.mdanalysis.org/blog/](https://www.mdanalysis.org/blog/)

- [x] Be kind: The project must be inclusive of all peoples.

MDAnalysis uses a code of conduct:
[https://www.mdanalysis.org/pages/conduct/
](https://www.mdanalysis.org/pages/conduct/)

MDAnalysis communicates with the public through
- mailing lists
- Twitter
- Github (issue tracker)
- a blog
- occasional tutorials/hackathons 

## Recommendation

Approve MDAnalysis for fiscal sponsorship.

**Comment by stefanv** [comment]
+1

**Comment by labarba** [comment]
+1

**Comment by kriehl** [comment]
+1

**Comment by xorJane** [comment]
Approved 4-0-0.
